spring.application.name=BikeRentalRideShare

spring.datasource.url=jdbc:postgresql://ep-quiet-flower-a14zl5av-pooler.ap-southeast-1.aws.neon.tech/bike_rental?user=bike_rental_owner&password=npg_QgDfd0TnF1Hj&sslmode=require
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.connection-timeout=1800000

jwt.secret=NTBmZjllZGFkMWJmZDg5ODYwYzU5NDUwMjEyNDlmZDcwOWE3N2QzNmU2ZTEzMTQ3NzY2NzhjMzUzZjA4NzkzZDdjNWRlYjE0ODg3ZDk4Mjc2YzcyZmMwODQ1ZGJlZWVlNzcyNTVhMGE3YzRjNjIwYWY5YjVkZmQ5Yjk5YmMwYWU1YTUyYzRkYjY3ODRkMzYyZDU1NWFhZmM4YWZkNWQ0NmE5NmM0ZTE4NTUyYjhiMzY0OWJhMzkyMTBiOTU2ZmNjZGM3MDMwYWRhOTNmZGUxNTU2YjU1ODkxZDA4MmUyYzZjOGJjYmM5YzIzOWI3ZmE4YzdkNWVjYjI3NzhlMmZjNQ==

# 10 hours
jwt.expiration=36000000

file.upload-dir=F:\\Java\\Projects\\BikeRentalRideShare\\src\\main\\java\\lk\\pgn265\\bikerentalrideshare\\storage